# Generated by Django 4.1.2 on 2022-10-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='numero_pasaporte',
            new_name='numero_documento',
        ),
        migrations.AlterField(
            model_name='familiar',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
