# Generated by Django 4.1.2 on 2022-10-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_rename_numero_pasaporte_familiar_numero_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='codigo_postal',
            field=models.IntegerField(default=1405),
            preserve_default=False,
        ),
    ]
